; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = esp32dev

[common]
framework = arduino
lib_deps = 
	br3ttb/PID@^1.2.1
	rubienr/HamlibRotctlEasycommParser@^0.1.3
    https://github.com/thijse/Arduino-Log.git
monitor_speed = 115200

[env:esp32dev]
extends = common
platform = espressif32
board = esp32dev

[env:atmelavr]
extends = common
platform = atmelavr
board = atmega328p
# some platforms require folat support for scanf/printf to be explicitely enabled
build_flags =
    # if platfrom is atmelavr:
    -Wl,-u,vfscanf,-lscanf_flt,-u,vfprintf,-lprintf_flt
    # if platform is [...]
